
#for some reason the script states that its missing the proper content. It could# be because the python_task_database is not create in the /home directory.
# attempts to mkdir /home/vagrant to workaround have not been successful
